### ISSUE TITLE
Classes in build/generated-src not regenerated automatically 

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision-examples#20] opened 2021-02-08 17:27 UTC
Steps to reproduce:
- Checkout template-fullstack-ktor
- `./gradlew clean build`
- --> fails with test compile error
- delete tests: `rm src/frontendTest/kotlin/test/ -R`
- `./gradlew build`
- --> build successfully
- `rm build/generated-src/ -R`
- `./gradlew build`
- --> Compile error related to the missing classes
- `./gradlew clean build` somehow seems to fix this issue again

**Comment by rjaros** [comment] 2021-02-08 17:45
The code in `generated-src` is created by the compiler plugin, which is executed during compilation phase. When you remove only this generated code, gradle apparently doesn't compile anything and doesn't execute the plugin (because it doesn't know it should). Perhaps it can be fixed somehow, but I don't gradle good enough to know how :-)

**Comment by jschneider** [comment] 2021-02-08 20:37
I run into the problem without removing the directory manually. I think it might be related to the build cache maybe?

**Comment by rjaros** [comment] 2022-09-13 16:41
The problem is now fixed with KSP plugin.

**Closed as completed by rjaros** 2022-09-13 16:41 UTC
