### ISSUE TITLE
Having problems run examples localy

### ISSUE THREAD

**Issue by dmarko484** [rjaros/kvision-examples#5] opened 2019-05-06 15:14 UTC
I have downloaded examples repo and trying to run todo example by calliing: gradlew.bat -t run in my Windows 10 machine. Seems some dependency cannot be downloaded see traceback below.  I tried for showcase example also and it failed on some other dependency. Any idea whats wrong here?

npm ERR! notarget No matching version found for kotlinx-serialization-runtime-js@0.11.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'build'
npm ERR! notarget

Fo showcase example I'm getting:
pm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/kvision-richtext - Not found
npm ERR! 404
npm ERR! 404  'kvision-richtext@0.0.35' is not in the npm registry.

**Comment by rjaros** [comment] 2019-05-06 18:16
Unfortunately I can't reproduce your problem. Have you checked all the [requirements](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up#requirements)?

On my Windows 10 machine I have installed:
- JDK 8u211 from Oracle
- NodeJS 10.15.3 LTS
- Git 2.21.0

I've cloned kvision-examples repository and the example applications (including todomvc and showcase) build and run without any problems.

If you have all the required tools, maybe you can give me more output logs. Try running gradle with --debug option.

**Comment by rojeras** [comment] 2019-06-04 15:28
I have the following installed:
`
➜  helloworld git:(master) java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
➜  helloworld git:(master) node --version
v12.3.1
➜  helloworld git:(master) npm --version
6.9.0
➜  helloworld git:(master) git --version 
git version 2.20.1 (Apple Git-117)`

I re-installed node, and removed all modules from /usr/local/lib/node_modules/npm, but nothing seems to help. It continues to complain about the missing kotlinx-serialization-runtime-js@0.11.0.

I attach the output from gradle --debug. 
[gradle-debug.log](https://github.com/rjaros/kvision-examples/files/3253200/gradle-debug.log)

**Comment by rjaros** [comment] 2019-06-04 15:47
Could you also attach /Users/leo/.npm/_logs/2019-06-04T15_22_22_753Z-debug.log ?

**Comment by rojeras** [comment] 2019-06-04 16:50
Attached. I really appreciate your help!
[2019-06-04T15_22_22_753Z-debug.log](https://github.com/rjaros/kvision-examples/files/3253554/2019-06-04T15_22_22_753Z-debug.log)

**Comment by rjaros** [comment] 2019-06-04 17:25
Could you please add an explicit dependency to your `build.gradle` file, so your `dependencies` section look like this:
```
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-js:${kotlinVersion}"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serializationVersion"
    compile "pl.treksoft:kvision:${kvisionVersion}"
    compile "pl.treksoft:kvision-i18n:${kvisionVersion}"
    testCompile "org.jetbrains.kotlin:kotlin-test-js:${kotlinVersion}"
}
```
Clean the project after that and try to rebuild. Let me know if it changes anything.

**Comment by rojeras** [comment] 2019-06-04 17:59
I created a fresh new clone, took a backup copy of helloworld and added the line to the dependencies. It still complains about the serialization-runtime-js:

➜  development git clone https://github.com/rjaros/kvision-examples.git
Cloning into 'kvision-examples'...
remote: Enumerating objects: 173, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 3727 (delta 112), reused 127 (delta 84), pack-reused 3554
Receiving objects: 100% (3727/3727), 15.91 MiB | 114.00 KiB/s, done.
Resolving deltas: 100% (1793/1793), done.
➜  development cd kvision-examples 
➜  kvision-examples git:(master) cp -rp helloworld helloworld_org
➜  kvision-examples git:(master) ✗ ls helloworld_org 
Gruntfile.js      gradle            gradlew           karma.config.d    package.json.d    src               webpack.config.d
build.gradle      gradle.properties gradlew.bat       package.json      settings.gradle   translation
➜  kvision-examples git:(master) ✗ cd helloworld
➜  helloworld git:(master) ✗ gvim build.gradle # To add the line in the dependencies section
➜  helloworld git:(master) ✗ ./gradlew run  
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :npm-install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for kotlinx-serialization-runtime-js@0.11.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'kvision'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2019-06-04T17_45_34_687Z-debug.log


> Task :npm-install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm-install'.
> npm install failed (exit code = 1)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 7s
3 actionable tasks: 3 executed
➜  helloworld git:(master) ✗ pwd
/Users/leo/Documents/data/Eternal/development/kvision-examples/helloworld
➜  helloworld git:(master) ✗ less build.gradle 
➜  helloworld git:(master) ✗ diff build.gradle ../helloworld_org/build.gradle 
41d40
<     compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serializationVersion"

------------------------------
The is attached.

[2019-06-04T17_45_34_687Z-debug.log](https://github.com/rjaros/kvision-examples/files/3253850/2019-06-04T17_45_34_687Z-debug.log)

**Comment by rjaros** [comment] 2019-06-04 21:48
Could you check, if you have symlink from `build/node_modules/kotlinx-serialization-runtime-js` to `build/node_modules_imported/kotlinx-serialization-runtime-js` (and other dirs in `node_modules_imported`)? If you do not have such symlinks, maybe you are running the build on some kind of network filesystem without support for symlinks?

**Comment by rojeras** [comment] 2019-06-05 06:30
Ah, it seems you solved it! 
The links are there. But I was running using a dropbox folder. When I cloned and tried to a fully local folder then it worked. 
I am very grateful for your help in this (and so is my wife who thinks I should not be "working" during our vacation ;)).

**Comment by rjaros** [comment] 2019-06-05 07:49
I'm glad I could help ! :)

**Closed as completed by rjaros** 2019-06-05 07:49 UTC
